### ISSUE TITLE
Open ai API link changes on restart

### ISSUE THREAD

**Issue by jimd-den** [Mobile-Artificial-Intelligence/maid#572] opened 2024-06-03 03:22 UTC
When using other API the link switches back to openai

**Comment by danemadsen** [comment] 2024-06-03 04:02
So to clarify is this when closing then restarting the app?

**Comment by jimd-den** [comment] 2024-06-03 22:18
actually when you select lama.cpp or anything else, it'll  reset the link, when you select a maid option. and yest just closing, everytime you close

**Comment by danemadsen** [comment] 2024-06-09 04:27
I cant reproduce this on the latest build?

**Comment by jimd-den** [comment] 2024-06-11 23:32
> I cant reproduce this on the latest build?

You are right, should've updated

**Closed** 2024-06-11 23:32 UTC
