### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by Phoenix1025** [Mobile-Artificial-Intelligence/maid#578] opened 2024-06-12 07:44 UTC
Can anyone leave a guide to use/setup this app on android for beginners and non technical experts like me.  Its even hard to get a model from the huggingface website using cellphone. So pls if anyone has time to put a step by step guide for newbies, it would be great. Thanks!

**Comment by predbrad** [comment] 2024-06-18 12:37
seems like a dupe of https://github.com/Mobile-Artificial-Intelligence/maid/issues/562

**Comment by danemadsen** [comment] 2024-06-19 05:42
dupe

**Closed by danemadsen** 2024-06-19 05:42 UTC
